displayName: Add Forwarded Headers
type: middleware
iconPath: .assets/icon.png

import: github.com/hiasr/forwardmiddleware

summary: 'Set X-Forwarded-For header if not already set to enable a working ipAllowList with both direct and indirect access.'

testData:
  Enabled: true
